# **Assignment For Numpy By Waqas Akram Reg# PIAIC143353**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [161]:
arr_1 = np.zeros(10)
print(arr_1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [162]:
arr_2 = np.arange(10,49)
print(arr_2)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [8]:
arr_2.shape

(39,)

5. Print the type of the previous array in question 3

In [10]:
arr_2.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [15]:
import numpy
numpy.version.version

'1.19.4'

7. Print the dimension of the array in question 3


In [17]:
arr_2.ndim

1

8. Create a boolean array with all the True values

In [22]:
arr_boolean = np.ones((5),dtype=bool)
print(arr_boolean)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [28]:
arr_2d = np.arange(30).reshape(6,5)
print(arr_2d)

2

10. Create a three dimensional array



In [33]:
arr_3d = np.arange(64).reshape(4,4,4)
print(arr_3d)

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [35]:
original_array = np.arange(1,7)
print("Original Vector ...")
print(original_array)
print("Reversed Vector...")
reversed_vector = original_array[::-1]
print(reversed_vector)

Original Vector ...
[1 2 3 4 5 6]
Reversed Vector...
[6 5 4 3 2 1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [37]:
null_vector = np.zeros(10)
print(null_vector)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [38]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [47]:
arr_int = np.array([1, 2, 3, 4, 5])
float_array = arr_int.astype('float64')
print(float_array.dtype)

float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [54]:
arr1 =  np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
multiplication = np.multiply(arr1,arr2)
print(multiplication)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [187]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
compare_array = (arr1 == arr2)
equal_new_array = compare_array.all()
print(equal_new_array)

False


17. Extract all odd numbers from arr with values(0-9)

In [62]:
simple_array = np.arange(0,9)
print("simple array",simple_array)
print("odd array ", simple_array[simple_array%2==1])


simple array [0 1 2 3 4 5 6 7 8]
odd array  [1 3 5 7]


18. Replace all odd numbers to -1 from previous array

In [64]:
print("odd array with negative multiplication ", simple_array[simple_array%2==1] * (-1))

odd array with negative multiplication  [-1 -3 -5 -7]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [67]:
arr = np.arange(10)
print(arr)
arr[5:9] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [69]:
original_ones = np.ones((4,4))
print("orginal ones matrix",original_ones)
print(" 1 on border and 0 inside ")
original_ones[1:-1,1:-1]=0
print(original_ones)

orginal ones matrix [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
 1 on border and 0 inside 
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [76]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(arr2d)
arr2d[1][1] = 12
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [71]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [103]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
first_1D_array = arr2d[:1]
print("1st 1 dimension array",first_1D_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1st 1 dimension array [[1 2 3]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [106]:
second_1D_array = arr2d[1]
print("1st 1 dimension array",second_1D_array)
second_value = second_1D_array[1]
print("2nd Value from 2nd 1D arr",second_value)

1st 1 dimension array [4 5 6]
2nd Value from 2nd 1D arr 5


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [108]:
slicing_out = arr2d[:2,:3]
slicing_out

array([[1, 2, 3],
       [4, 5, 6]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [98]:
random_matrix = np.random.random((10,10))
print("Random Matrix ")
print(random_matrix)
print("Maximum Value ", random_matrix.max())
print("Minimum Value ", random_matrix.min())

Random Matrix 
[[0.51739467 0.54904368 0.8166132  0.3811291  0.92400303 0.54983835
  0.35315782 0.42252205 0.83447994 0.07879889]
 [0.67480207 0.20784209 0.49921582 0.96681745 0.09633515 0.02329697
  0.88357222 0.11526776 0.572459   0.47386772]
 [0.81509867 0.73790332 0.86803109 0.17840936 0.46222634 0.65228326
  0.14507797 0.82403696 0.02415426 0.25940296]
 [0.45068465 0.37591737 0.1984373  0.52409137 0.0694135  0.38283327
  0.97176526 0.05323203 0.88656095 0.43018717]
 [0.70184143 0.16364859 0.8954356  0.19871139 0.65778529 0.90776354
  0.50938899 0.82598248 0.92458935 0.21876922]
 [0.02892576 0.78728468 0.66640336 0.07124759 0.61555725 0.20511614
  0.70374114 0.93056022 0.16707183 0.20606249]
 [0.06041399 0.09311786 0.23661596 0.43023823 0.34249717 0.60562535
  0.61938239 0.40828906 0.97040168 0.24116871]
 [0.01846221 0.37152517 0.64739987 0.55909651 0.97640585 0.39917204
  0.22693025 0.94380944 0.84692962 0.48578132]
 [0.02624601 0.96724834 0.2131071  0.49457496 0.06791114 0.206468

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [100]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a,b)
print(common_items)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [15]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
matching_items = np.intersect1d(a,b)
print("Common Values \n",matching_items)
print("Positions \n",np.where(matching_items==matching_items))

Common Values 
 [2 4]
Positions 
 (array([0, 1]),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [154]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
not_equal_condition = (names != "Will")
print(not_equal_condition)
data[not_equal_condition]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.02543637  0.49585659  0.11472671  0.16190716]
 [ 0.348922   -1.3189847   0.23764072  0.15992327]
 [-0.22989495 -1.81721936  0.09342875  0.1756266 ]
 [ 0.16913611  0.32913079  1.34019428 -0.18058159]
 [-0.10978689 -2.91151296 -1.90440931  0.48925674]
 [-0.21836368 -0.64855044 -0.42316574  0.1910652 ]
 [ 0.1756953   0.26429195  2.21377746  1.04314245]]
[ True  True False  True False  True  True]


array([[-1.02543637,  0.49585659,  0.11472671,  0.16190716],
       [ 0.348922  , -1.3189847 ,  0.23764072,  0.15992327],
       [ 0.16913611,  0.32913079,  1.34019428, -0.18058159],
       [-0.21836368, -0.64855044, -0.42316574,  0.1910652 ],
       [ 0.1756953 ,  0.26429195,  2.21377746,  1.04314245]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [116]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
not_equal_condition = (names != "Will") & (names !="Joe")
print(not_equal_condition)
data[not_equal_condition]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-1.58028468 -1.05893428  1.35845821 -0.31761838]
 [-0.13800589 -0.45266843 -0.86553889  0.93735731]
 [-2.50011098 -1.00726439  0.40371238 -0.49915184]
 [-0.95781993  0.34888642  1.8146147  -0.79601822]
 [ 0.0242847  -0.88883817  1.34881375  0.1686998 ]
 [-1.23319228 -0.08268034 -0.02497536 -0.88273107]
 [ 0.46381316  0.74497697  0.98009818  0.43743359]]
[ True False False  True False False False]


array([[-1.58028468, -1.05893428,  1.35845821, -0.31761838],
       [-0.95781993,  0.34888642,  1.8146147 , -0.79601822]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [117]:
random_decimal_2d = np.random.uniform(5,10, size=(5,3)
print(random_decimal_2d)

[[5.11215811 7.01452185 9.61829527]
 [5.07855722 5.43889763 9.31716328]
 [7.87720115 5.43897758 7.87221461]
 [9.51464887 5.91105841 7.51962975]
 [7.70721286 6.3884894  9.47007446]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [138]:
random_decimal_new = np.random.uniform(1,16,size=(2,2,4))
print(random_decimal_new)

[[[ 5.48712703  3.99403349  7.89836607  2.78851606]
  [11.13957596  1.50494529  6.53066739  6.91723394]]

 [[ 5.62808106 10.84837118  3.15133591 10.91932659]
  [12.26237512  9.17351592  3.5173159   3.73234317]]]


33. Swap axes of the array you created in Question 32

In [139]:
swaping_axes = random_decimal_new.T
print(swaping_axes)

[[[ 5.48712703  5.62808106]
  [11.13957596 12.26237512]]

 [[ 3.99403349 10.84837118]
  [ 1.50494529  9.17351592]]

 [[ 7.89836607  3.15133591]
  [ 6.53066739  3.5173159 ]]

 [[ 2.78851606 10.91932659]
  [ 6.91723394  3.73234317]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [153]:
normal_array = np.arange(10)
print(normal_array,"\n")
sqrt_array = np.sqrt(normal_array)
print(sqrt_array,"\n")
for i in sqrt_array:
    if i<0.5:
        i=0
    print(i)


[0 1 2 3 4 5 6 7 8 9] 

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 

0
1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [163]:
first_random_array = np.random.randn(12)
second_random_array = np.random.randn(12)
new_maximum_random = np.maximum(first_random_array,second_random_array)
print(new_maximum_random)

[-0.10019478  0.17137701  0.43916773  0.1049647   0.75793405  1.783618
  1.29332926  0.5129032  -0.8646209   0.86507177  1.34059978  0.53817647]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [165]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names)
print("unique names\n",unique_names)
print("Sorted Unique Names \n",sorted(set(names)))

unique names
 ['Bob' 'Joe' 'Will']
Sorted Unique Names 
 ['Bob', 'Joe', 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [186]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
difference = np.setdiff1d(a,b)
print(difference)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [6]:

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray = np.delete(sampleArray,2,axis=0)
print(sampleArray)
newColumn = np.array([[10,10,10]])
new_array_matrix = np.append(sampleArray,newColumn,axis=0)
print(new_array_matrix)

[[34 43 73]
 [82 22 12]]
[[34 43 73]
 [82 22 12]
 [10 10 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [166]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot_product = np.dot(x,y)
print(dot_product)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [171]:
random_new_matrix = np.random.randn(20)
print("Random Matrix \n ================")
print(random_new_matrix)
print("Cumulative Sum \n ================")
cumulative_sum = np.cumsum(random_new_matrix)
print(cumulative_sum)

Random Matrix 
[ 1.62874504 -1.87070193  0.06556371  0.1704504   1.27682818 -0.32231818
 -0.49341362  0.52767782 -1.62294525 -1.16922293 -1.89930717  1.27546281
  1.62552427 -1.28176528  0.87126455 -1.35975616  0.2738973   2.5767855
  0.4154358   2.38660497]
Cumulative Sum 
[ 1.62874504 -0.24195689 -0.17639317 -0.00594277  1.27088541  0.94856724
  0.45515361  0.98283144 -0.64011382 -1.80933675 -3.70864392 -2.43318111
 -0.80765684 -2.08942212 -1.21815756 -2.57791372 -2.30401642  0.27276908
  0.68820487  3.07480984]
