# Numpy_Assignment_2 By Waqas Akram Reg# PIAIC143353

## Question:1

In [ ]:
import numpy as np

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
import numpy as np
arr_1d = np.arange(10)
print(arr_1d)
arr_2d = arr_1d.reshape(2,5)
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [8]:
#for stacking The arrays must have the same shape along all but the first axis. 1-D arrays must have the same length.
arr_1 = np.array([2,4,5])
arr_2 = np.array([3,7,9])
vertical_stack_of_array = np.vstack((arr_1,arr_2))
print(vertical_stack_of_array)

[[2 4 5]
 [3 7 9]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [6]:
arr_1 = np.array([2,4,5])
arr_2 = np.array([3,7,9])
horizontal_stack_of_array = np.hstack((arr_1,arr_2))
print(horizontal_stack_of_array)

[2 4 5 3 7 9]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [9]:
initial_array = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) 
print("Original Initial Array \n")
print(initial_array)
flat_Array = initial_array.flatten()
print("Flatted Array ",flat_Array)

Original Initial Array 

[[1 2 3]
 [2 4 5]
 [1 2 3]]
Flatted Array  [1 2 3 2 4 5 1 2 3]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [16]:
high_Dimension = np.arange(64).reshape(4,4,4)
print(high_Dimension,"\n")
print("Only one Dimension\n\n",high_Dimension.ravel())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]] 

Only one Dimension

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [24]:
one_dimension = np.arange(125)
print ("Dimension = ",one_dimension.ndim)
higher_dimension = one_dimension.reshape(5,5,5)
print("Dimension ",higher_dimension.ndim)

Dimension =  1
Dimension  3


## Question:7

### Create 5x5 an array and find the square of an array?

In [36]:
simple_array = np.random.random((5,5))*1000
print("Simple initial Array \n\n")
print(simple_array,"\n\n")
squares_of_array = np.square(simple_array)
print("Squares \n\n")
print(squares_of_array)


Simple initial Array 


[[256.59881732 164.01619783 531.61343926 753.02470475 688.06711976]
 [415.34831749 588.93312953 496.42963566 634.38209903 808.35732405]
 [755.84691103 241.85762012 195.26405633 547.62528809 541.64112838]
 [ 44.8874155  168.66248534 617.24660312 876.490002   804.84531701]
 [474.59170613 305.47507069 547.63910027 790.85418328 409.90908476]] 


Squares 


[[ 65842.95305104  26901.31314974 282612.84880516 567046.20596579
  473436.36129671]
 [172514.22484278 346842.23105275 246442.38316181 402440.64756635
  653441.56333852]
 [571304.55291656  58495.10840858  38128.05169596 299893.45615848
  293375.11195708]
 [  2014.88007009  28447.03396094 380993.369067   768234.72360973
  647775.9843186 ]
 [225237.28752497  93315.01881193 299908.58414254 625450.33921262
  168025.45776622]]


## Question:8

### Create 5x6 an array and find the mean?

In [41]:
radom_array = np.random.random((5,6))
print("Random Array \n \n",radom_array)
mean_of_array = np.mean(radom_array)
print("\n\nMean = ",mean_of_array)

Random Array 
 
 [[0.48504937 0.83798894 0.45304695 0.38532957 0.65773694 0.63682056]
 [0.78499199 0.85910212 0.4031863  0.19133103 0.85377983 0.07712074]
 [0.04109308 0.35886291 0.72262774 0.2354983  0.53399661 0.87463919]
 [0.36543344 0.79350744 0.00782329 0.58140666 0.44806574 0.05127078]
 [0.45548146 0.00698819 0.67393018 0.07137093 0.58811662 0.56033618]]


Mean =  0.46653110299335093


## Question:9

### Find the standard deviation of the previous array in Q8?

In [42]:
standard_deviation = np.std(radom_array)
print("Standard Deviation = ",standard_deviation)

Standard Deviation =  0.2755459833985996


## Question:10

### Find the median of the previous array in Q8?

In [43]:
median = np.median(radom_array)
print("Median = ",median)

Median =  0.47026541778800995


## Question:11

### Find the transpose of the previous array in Q8?

In [45]:
transpose_of_array = radom_array.T
print(transpose_of_array)

[[0.48504937 0.78499199 0.04109308 0.36543344 0.45548146]
 [0.83798894 0.85910212 0.35886291 0.79350744 0.00698819]
 [0.45304695 0.4031863  0.72262774 0.00782329 0.67393018]
 [0.38532957 0.19133103 0.2354983  0.58140666 0.07137093]
 [0.65773694 0.85377983 0.53399661 0.44806574 0.58811662]
 [0.63682056 0.07712074 0.87463919 0.05127078 0.56033618]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [66]:
normal_array = np.arange(16).reshape(4,4)
print("4x4 Matrix \n \n",normal_array)
diagonal_matrix = np.diag(normal_array)
print("Diagonal Elements : ",diagonal_matrix) #extract diagonal elements
diagonal_matrix = np.sum(diagonal_matrix) #finding Sum here
print("Sum of Diagonal = ",diagonal_matrix)



4x4 Matrix 
 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Diagonal Elements :  [ 0  5 10 15]
Sum of Diagonal =  30


## Question:13

### Find the determinant of the previous array in Q12?

In [68]:
determinat = np.linalg.det(normal_array)
print("Determinant = ",determinat)

Determinant =  0.0


## Question:14

### Find the 5th and 95th percentile of an array?

In [70]:
given_array = np.arange(12)
print("Given Array   : ",given_array)
percentile_5th = np.percentile(given_array,5)
percentile_95th = np.percentile(given_array,95)
print("5th Percentile  = ",percentile_5th,"%")
print("95th Percentile  ",percentile_95th,"%")

Given Array   :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
5th Percentile  =  0.55 %
95th Percentile   10.45 %


## Question:15

### How to find if a given array has any null values?

In [78]:
#We can find out by using function isnan() importing from numpy
simple_array = np.arange(5)
print(np.isnan(simple_array)) #this will return boolean values ,, if null present it returns true otherwise false

[False]
